### PR TITLE
Removed ParseInit() which should be handled by the timeline parser no…

### PR DESCRIPTION
**Pull request by Areustle**
…w. Replaced MakeAttTako()'s parser with calls to the timeline object.

Hey Joe, Let's see what it's like to handle a merge request in github!!

### CODE REVIEW

**Comment by Areustle** [comment]
So we can talk about changes here. When we're confident that it's good to go we can click the big green "MERGE PULL REQUEST" button and merge them into the branch.

**Comment by jasercion** [comment]
Ok, reading through the diff now.  Here's some example comment.

**Comment by Areustle** [comment]
unfortunately it really misunderstood the diff of my changes.

**Review by jasercion — APPROVED** [review]
Looks good to me, let's roll the dice.

**Pull request merged**
